# : Manager [[[

[manager]
cwd = { fg = "#e0e2ef" }

# Tab
tab_active = { fg = "#003640", bg = "#55d6f4", bold = true }
tab_inactive = { fg = "#acedff", bg = "#001f26" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#7296ff", bg = "#7296ff" }
marker_cut = { fg = "#d8e2ff", bg = "#d8e2ff" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#aec6ff", bg = "#aec6ff" }

# Count
count_copied = { fg = "#001a43", bg = "#d8e2ff" }
count_cut = { fg = "#001a43", bg = "#d8e2ff" }
count_selected = { fg = "#003640", bg = "#aec6ff" }

# Border
border_symbol = "│"
border_style  = { fg = "#55d6f4" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#003640", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#55d6f4", fg = "#003640", bold = true }
normal_alt  = { bg = "#3f4759", fg = "#bfc6dc" }

# Select mode
select_main = { bg = "#85d2e7", fg = "#003640", bold = true }
select_alt  = { bg = "#3f4759", fg = "#bfc6dc" }

# Unset mode
unset_main = { bg = "#aec6ff", fg = "#122f60", bold = true }
unset_alt  = { bg = "#3f4759", fg = "#bfc6dc" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#55d6f4", bg = "#353943" }
progress_error = { fg = "#ffb4ab", bg = "#353943" }

# Permissions
permissions_t = { fg = "#2392b0" }
permissions_w = { fg = "#155aff" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#3f70ff" }
permissions_s = { fg = "#13ccff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#55d6f4" }
active = { fg = "#aec6ff", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#55d6f4" }
value = { fg = "#e0e2ef" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#55d6f4", bg = "#003640" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#55d6f4" }
title = {}
hovered = { fg = "#d8e2ff", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#353943" }
cand = { fg = "#55d6f4" }
rest = { fg = "#003640" }
desc = { fg = "#e0e2ef" }
separator = " ▶ "
separator_style = { fg = "#e0e2ef" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e0e2ef" }
run = { fg = "#e0e2ef" }
footer = { fg = "#003640", bg = "#85d2e7" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#aec6ff" }
title_warn = { fg = "#55d6f4" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e0e2ef" },
    { name = "*/", fg = "#55d6f4" },
]

# : ]]]