"$schema" = "https://starship.rs/config-schema.json"
add_newline = true
palette = "matugen"
format = """
[┏](fg:frame)\
$time\
$directory\
$git_branch\
$git_status\
$git_state\
$cmd_duration\
[<](fg:frame)
[┗](fg:frame)\
$character"""
[palettes.matugen]
frame = "#959181"
path = "#d7c870"
branch = "#cfc7a2"
success = "#d7c870"
warning = "#a8d0b6"
danger = "#ffb4ab"
muted = "#ccc6b5"
text = "#e8e2d4"
[time]
disabled = false
time_format = "%H:%M"
format = "[ $time ](bold fg:text)[─](fg:frame)"
[directory]
format = "[  󰉋  $path ]($style)"
style = "bold fg:path"
truncation_length = 4
truncation_symbol = "…/"
read_only = " "
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "
[git_branch]
symbol = " "
format = "[─](fg:frame)[ $symbol$branch ]($style)"
style = "bold fg:branch"
truncation_length = 32
only_attached = false
[git_status]
format = "[$all_status$ahead_behind ]($style)"
style = "bold fg:warning"
conflicted = "=${count} "
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
untracked = "?${count} "
stashed = "≡${count} "
modified = "!${count} "
staged = "+${count} "
renamed = "»${count} "
deleted = "✘${count} "
[git_state]
format = '[ \($state( $progress_current/$progress_total)\) ](bold fg:danger)'
[cmd_duration]
min_time = 1000
format = "[ $duration ](fg:muted)"
[character]
success_symbol = "[ >](bold fg:success)"
error_symbol = "[ >](bold fg:danger)"
vimcmd_symbol = "[ >](bold fg:success)"
vimcmd_replace_one_symbol = "[ >](bold fg:warning)"
vimcmd_replace_symbol = "[ >](bold fg:danger)"
vimcmd_visual_symbol = "[ >](bold fg:branch)"
format = "$symbol "

